name: Build Whitehole

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name : Checkout Repo
      uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Install Apache Ant
      run : choco install ant --acceptlicense --confirm
    - name: Insatll cURL
      run: choco install curl --acceptlicense --confirm
    - name: Build Whitehole
      run: Build.cmd
      shell: cmd
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: "Build.zip"
    - name: Make a release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "auto"
        prerelease: true
        title: "Auto Build"
        files: |
          Build.zip
